"""Database creation.

Revision ID: 1a74ab6b9941
Revises: 
Create Date: 2023-10-20 20:33:39.588048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a74ab6b9941'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commands',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('command', sa.String(), nullable=True),
                    sa.Column('response', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_commands_command'), 'commands', ['command'], unique=True)
    op.create_index(op.f('ix_commands_id'), 'commands', ['id'], unique=False)
    op.create_table('messages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('message', sa.String(), nullable=True),
                    sa.Column('response', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_message'), 'messages', ['message'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_message'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_commands_id'), table_name='commands')
    op.drop_index(op.f('ix_commands_command'), table_name='commands')
    op.drop_table('commands')
    # ### end Alembic commands ###
